dist: trusty
sudo: false
language: python
python:
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
matrix:
  allow_failures:
  - python: "3.7-dev"
cache: pip
install:
- pip install pydiatra pyflakes
- pip install websocket-client
script:
- python3 -m pydiatra .
- python3 -m pyflakes .
- export PAGER=cat
- ./dcs-cli -w '[0-9]*[2-9][1-3]th' filetype:perl

# vim:ts=2 sts=2 sw=2 et
