dist: xenial
language: python
python:
- "3.4"
- "3.5"
- "3.6"
- "3.7"
cache: pip
install:
- python3 -m pip install websocket-client
- python3 -m pip install pydiatra pyflakes
- python3 -m pip install restructuredtext-lint pygments
script:
- export PAGER=cat
- ./dcs-cli -w '[0-9]*[2-9][1-3]th' filetype:perl
- python3 -m pydiatra .
- python3 -m pyflakes .
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
